---
title: "EVPI for external validation"
author: "Mohsen Sadatsafavi"
date: "2022.06.02"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('./R/core.R')
```


```{r}

  library(voipred)
  library(rms)
  library(mvtnorm)
  library(pROC)
  set.seed(123) #123 #3344 #123456


settings <- list(
  dev_sample_size = Inf,
  val_sample_size = 500,
  n_sim=1000,
  Bayesian_bootstrap =T,
  zs=c(0.01,0.05,0.1,0.02),
  max_x_evpi_plot = 0.2   #For plots of evpi 
)

  data(gusto)
  gusto$kill <- (as.numeric(gusto$Killip)>1)*1
  gusto$Y <- gusto$day30
  data_us <- gusto[gusto$regl %in% c(1, 7, 9, 10, 11, 12, 14, 15),]
  data_other <- gusto[!gusto$regl %in% c(1, 7, 9, 10, 11, 12, 14, 15),]
  
  if(is.infinite(settings$dev_sample_size))
  {
    dev_data <- data_other
  }else
  {
    dev_data <- data_other[sample(1:(dim(data_other)[1]),settings$dev_sample_size,F),]
  }
  
  if(is.infinite(settings$val_sample_size))
  {
    val_data <- data_us
  }else
  {
    val_data <- data_us[sample(1:(dim(data_us)[1]),settings$val_sample_size,F),]  #data is for external validation
  }
  
  #model <- glm(Y ~ age + miloc + pmi + kill + pmin(sysbp,100) + lsp(pulse,50), data=dev_data, family=binomial(link="logit"))
  model <- glm(Y ~ age + miloc + pmi + kill + pmin(sysbp,100) + pulse, data=dev_data, family=binomial(link="logit"))
  
  pi <- predict(model, type="response", newdata=val_data)
  pi <- 1/(1+exp(0-(log(pi/(1-pi)))))
  val_data$pi <- pi
  
  zs <- (c(as.vector(quantile(pi,(1:99)/100)),settings$zs))
  main_index <- length(zs)
```


### Candidate model's coefficients and c-statistic
```{R}
coefficients(model)
pROC::auc(val_data$Y,val_data$pi)
```




### DCA with bootstrap CIs
```{R}
  n <- dim(val_data)[1]
  NBh_model <- NBh_all <- rep(0,length(zs))
  for(i in 1:length(zs))
  {
    NBh_model[i] <- mean((val_data$pi>zs[i])*(val_data$Y - (1-val_data$Y)*zs[i]/(1-zs[i])))
    NBh_all[i] <- mean((val_data$Y - (1-val_data$Y)*zs[i]/(1-zs[i])))
  }

#   max_y <- max(0,NBh_all,NBh_model)
#   min_y <- min(NBh_model)
#   plot(zs, NBh_all, col='black', type='l', ylim=c(min_y,max_y))
#   lines(zs, zs*0, col='grey', type='l')
#   lines(zs, NBh_model, col='blue', type='l')
# 
# #And now uncertainty around it
  bs_NBh_model <- bs_NBh_all <- matrix(0, nrow=settings$n_sim, ncol=length(zs))

  for(i_sim in 1:settings$n_sim)
  {
    w <- voipred:::bootstrap(n,settings$Bayesian_bootstrap)
    
    for(i in 1:length(zs))
    {
      bs_NBh_model[i_sim,i] <- sum(w*(val_data$pi>zs[i])*(val_data$Y - (1-val_data$Y)*zs[i]/(1-zs[i])))/n
      bs_NBh_all[i_sim,i] <- sum(w*(val_data$Y - (1-val_data$Y)*zs[i]/(1-zs[i])))/n
    }
  }
  
  NBh_all <- colMeans(bs_NBh_all)
  NBh_model <- colMeans(bs_NBh_model)
  
  max_y <- max(0,NBh_all[1:99],NBh_model[1:99])
  plot(zs[1:99], NBh_all[1:99], col='black', type='l', ylim=c(0,max_y), xlab="Risk threshold", ylab="Net benefit")
  lines(zs[1:99], zs[1:99]*0, col='black', type='l')
  lines(zs[1:99], NBh_model[1:99], col='blue', type='l')
  ci_model <- apply(bs_NBh_model[,1:99],MARGIN = 2,FUN = quantile, c(0.025,0.975))
  lines(zs[1:99],ci_model[1,], type='l', col='gray')
  lines(zs[1:99],ci_model[2,], type='l', col='gray')
```



### Difference in NB and 95%CI
```{R}
quantile(bs_NBh_model[,main_index]-bs_NBh_all[,main_index],c(0.025,0.975))
sum(bs_NBh_model[,main_index]-bs_NBh_all[,main_index]>0)/length(bs_NBh_model[,main_index])
hist(bs_NBh_model[,main_index]-bs_NBh_all[,main_index], xlab="Incremental NB", ylab="Density", main="")
```


### Values of decision at threshold values of interest:
```{R}
rbind(z=settings$zs,NB_model=NBh_model[-(1:99)],NB_all=NBh_all[-(1:99)],INB=NBh_model[-(1:99)]-NBh_all[-(1:99)])
```



### EVPIv - Bayesian bootsrap
```{R}
  res_bb <- voi_ex_glm(model,val_data,method='bootstrap',Bayesian_bootstrap = T, zs = zs)
  
  plot(zs[1:99],res_bb$EVPIv[1:99],type='l', xlim=c(0,settings$max_x_evpi_plot), ylim=c(0,max(res_bb$EVPIv[which(zs<=settings$max_x_evpi_plot)])),col='red', lwd=2)
```


### EVPIv - Ordinary bootsrap
```{R}
  res_ob <- voi_ex_glm(model,val_data,method='bootstrap',Bayesian_bootstrap = F,zs = zs)
  
  plot(zs[1:99],res_ob$EVPIv[1:99],type='l', xlim=c(0,settings$max_x_evpi_plot), ylim=c(0,max(res_ob$EVPIv[which(zs<=settings$max_x_evpi_plot)])),col='blue', lwd=2)
```


###  Asymptotic approach
```{R}
  res_as <- voi_ex_glm(model,val_data,method='asymptotic',zs = zs)
  plot(zs[1:99],res_as$EVPIv[1:99],type='l', xlim=c(0,settings$max_x_evpi_plot), ylim=c(0,max(res_as$EVPIv[which(zs<=settings$max_x_evpi_plot)])),col='orange', lwd=2)
```



###  Reference modeling approach
```{R eval=F}
  res_mb <- voi_ex_glm(model,val_data,method='model_based_bs',Bayesian_bootstrap = F,zs = zs)
  plot(zs,res_mb$EVPIv,type='l', col='blue', xlim=c(0,settings$max_x_evpi_plot), ylim=c(0,max(res_mb$EVPIv[which(zs<=settings$max_x_evpi_plot)])))
```


### Combined graph for EVPIv
```{R}
max_y <- max(c(res_bb$EVPIv[zs<=settings$max_x_evpi_plot],res_ob$EVPIv[zs<=settings$max_x_evpi_plot],res_as$EVPIv[zs<=settings$max_x_evpi_plot]))
plot(zs[1:99],res_bb$EVPIv[1:99],type='l', col='red',xlim=c(0,settings$max_x_evpi_plot), lwd=2, ylim=c(0,max_y), xlab="Risk threshold", ylab="EVPI")
lines(zs[1:99],res_ob$EVPIv[1:99],type='l', col='blue', lwd=2)
#lines(zs,res_mb$EVPIv,type='l', col='red')
lines(zs[1:99],res_as$EVPIv[1:99],type='l', col='orange', lwd=2)

```


### P(useful)
```{R}
max_y <- max(c(res_bb$p_useful[zs<=settings$max_x_evpi_plot],res_ob$p_useful[zs<=settings$max_x_evpi_plot],res_as$p_useful[zs<=settings$max_x_evpi_plot]))
plot(zs[1:99],res_bb$p_useful[1:99],type='l', col='red',xlim=c(0,settings$max_x_evpi_plot), lwd=2, ylim=c(0,max_y), xlab="Risk threshold", ylab="P(useful)")
lines(zs[1:99],res_ob$p_useful[1:99],type='l', col='blue', lwd=2)
#lines(zs,res_mb$EVPIv,type='l', col='red')
#lines(zs[1:99],res_as$p_useful[1:99],type='l', col='orange', lwd=2)
rbind(z=settings$zs,p_useful_bb=res_bb$p_useful[-(1:99)],p_useful_bb=res_ob$p_useful[-(1:99)])
```


### EVPI at preferred threhsolds
```{r}
rbind(z=settings$zs,EVPIv_bb=res_bb$EVPIv[-(1:99)],EVPIv_ob=res_ob$EVPIv[-(1:99)],EVPIv_as=res_as$EVPIv[-(1:99)])
```



