---
title: "EVPI for external validation"
author: "Mohsen Sadatsafavi"
date: "2022.06.22"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('./R/core.R')
```


```{r,message=F}

  library(voipred)
  library(rms)
  library(mvtnorm)
  library(pROC)
  set.seed(123) #123 #3344 #123456


settings <- list(
  dev_sample_size = Inf,
  val_sample_size = 500,
  n_sim=10000,
  Bayesian_bootstrap =T,
  zs=c(0.01,0.05,0.1,0.02),
  max_x_evpi_plot = 0.2   #For plots of evpi 
)

  data(gusto)
  gusto$kill <- (as.numeric(gusto$Killip)>1)*1
  gusto$Y <- gusto$day30
  data_us <- gusto[gusto$regl %in% c(1, 7, 9, 10, 11, 12, 14, 15),]
  data_other <- gusto[!gusto$regl %in% c(1, 7, 9, 10, 11, 12, 14, 15),]
  
  if(is.infinite(settings$dev_sample_size))
  {
    dev_data <- data_other
  }else
  {
    dev_data <- data_other[sample(1:(dim(data_other)[1]),settings$dev_sample_size,F),]
  }
  
  if(is.infinite(settings$val_sample_size))
  {
    val_data <- data_us
  }else
  {
    val_data <- data_us[sample(1:(dim(data_us)[1]),settings$val_sample_size,F),]  #data is for external validation
  }
  
  #model <- glm(Y ~ age + miloc + pmi + kill + pmin(sysbp,100) + lsp(pulse,50), data=dev_data, family=binomial(link="logit"))

model <- glm(Y ~ age + miloc + pmi + kill + pmin(sysbp,100) + pulse, 
             data=dev_data, 
             family=binomial(link="logit"))
```


### Asymptotic method
```{R check}
asym_method <- function(model,val_data,zs=c(0.01)){
  
  N <- nrow(val_data)
  
  ENB_perfect <- ENB_current <- rep(0, length(zs))
  
  for(j in 1:length(zs)){
    
    z <- zs[j]
    tilde_z <- z/(1-z)
    pi <- val_data$pi
    Y <- val_data$Y
    NB_model <- sum(as.numeric(pi>z)*(Y-(1-Y)*tilde_z))/N
    NB_all <- sum(Y-(1-Y)*tilde_z)/N
    
    parms <- NB_BVN(Y,pi,z, NULL)
    
    if(is.na(parms[5])){
      ENB_perfect[j] <- ENB_current[j] <- max(0,NB_model,NB_all)
    } else{
      if(parms[5]>0.999999) parms[5]<- 0.999999
      if(parms[5]< -0.999999) parms[5]<- -0.999999

      tryCatch(
        {ENB_perfect[j] <- do.call(mu_max_truncated_bvn,as.list(parms))}
      , error=function(cond) {
        return(NULL)
      })
      
      ENB_current[j] <- max(0,NB_model,NB_all)
    }
  }
  
  return(data.frame(sample_size= N,z=zs, ENB_perfect=ENB_perfect, 
                      ENB_current=ENB_current, 
                      EVPIv=ENB_perfect-ENB_current))
}

val_sample_sizes <- c(250,500,1000,2000,4000,8000,16000,Inf)

results <- NULL
set.seed(123)
N_sim <- 1000
zs <- c(0.01,0.02,0.05,0.1)

for (j in 1:N_sim){
  
  for(i in 1:length(val_sample_sizes)){
    
    val_sample_size <- val_sample_sizes[i]
    
    if(is.infinite(val_sample_size)){
      val_data <- data_us
    }else{
      val_data <- data_us[sample(1:(dim(data_us)[1]),val_sample_size,F),]  #data is for external validation
    }
    
    val_data$pi <- predict(model, type="response", newdata=val_data)
    tmp_result <- asym_method(model,val_data,
                                         zs=zs)
    tmp_result$iter <- j
    results <- rbind(results,tmp_result)
  }
  # cat(".")
}

library(dplyr)
final_results <- results %>% 
  as.data.frame()

df_results <- data.frame(sample_size = final_results$sample_size %>% unlist(),
                         iter = final_results$iter %>% unlist(),
                         EVPIv=final_results$EVPIv %>% unlist(),
                         z= final_results$z %>% unlist()) %>% 
  group_by(sample_size,z) %>% 
  summarise(EVPIv=mean(EVPIv))

ggplot(data=df_results,aes(x=sample_size,y=EVPIv))+
  geom_point() +
  geom_line()+
  facet_grid(.~z)
```




