---
title: "Second attempt (From scratch)"
author: "Mohsen Sadatsafavi"
date: "2022.02.20"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
settings <- list(
  dev_sample_size = Inf,
  val_sample_size = 1000,
  n_sim_bs = 1000,
  n_sim_un = 100,
  n_sim_mb = 1000,
  Bayesian_bootstrap =T,
  z=0.02
)

```



```{r}
  library(voipred)
  library(rms)

  set.seed(1)

  data(gusto)
  gusto$kill <- (as.numeric(gusto$Killip)>1)*1
  gusto$Y <- gusto$day30
  data_us <- gusto[gusto$regl %in% c(1, 7, 9, 10, 11, 12, 14, 15),]
  data_other <- gusto[!gusto$regl %in% c(1, 7, 9, 10, 11, 12, 14, 15),]
  
  if(is.infinite(settings$dev_sample_size))
  {
    dev_data <- data_other
  }else
  {
    dev_data <- data_other[sample(1:(dim(data_other)[1]),settings$dev_sample_size,F),]
  }
  
  if(is.infinite(settings$val_sample_size))
  {
    val_data <- data_us
  }else
  {
    val_data <- data_us[sample(1:(dim(data_us)[1]),settings$val_sample_size,F),]  #data is for external validation
  }
  
  model1 <- glm(Y ~ age + miloc + pmi + kill + pmin(sysbp,100) + lsp(pulse,50), data=dev_data, family=binomial(link="logit"))
  pi <- predict(model1, type="response", newdata=val_data)
  val_data$pi1 <- pi
  val_data$logit_pi1 <- log(pi/(1-pi))
  
  model2 <- glm(Y ~ age + miloc + pmi + kill + pmin(sysbp,100) + lsp(pulse,50) + htn + smk + prevcabg + prevcvd, data=dev_data, family=binomial(link="logit"))
  pi <- predict(model2, type="response", newdata=val_data)
  val_data$pi2 <- pi
  val_data$logit_pi2 <- log(pi/(1-pi))
  
  zs <- quantile(pi,(0:99)/100)
  n <- dim(val_data)[1]
```


### Bootstrap approach
```{R}
  NBh_model1 <- NBh_model2 <- NBh_all <- rep(0,length(zs))
  for(i in 1:length(zs))
  {
    NBh_model1[i] <- mean((val_data$pi1>zs[i])*(val_data$Y - (1-val_data$Y)*zs[i]/(1-zs[i])))
    NBh_model2[i] <- mean((val_data$pi2>zs[i])*(val_data$Y - (1-val_data$Y)*zs[i]/(1-zs[i])))
    NBh_all[i] <- mean((val_data$Y - (1-val_data$Y)*zs[i]/(1-zs[i])))
  }

  max_y <- max(0,NBh_all,NBh_model1,NBh_model2)
  min_y <- min(c(NBh_model1,NBh_model2))
  plot(zs, NBh_all, col='black', type='l', ylim=c(min_y,max_y))
  lines(zs, zs*0, col='grey', type='l')
  lines(zs, NBh_model1, col='blue', type='l')
  lines(zs, NBh_model2, col='green', type='l')

#And now uncertainty around it
  bs_NBh_model1 <- bs_NBh_model2 <- bs_NBh_all <- bs_max_NBh <- matrix(0, nrow=settings$n_sim_bs, ncol=length(zs))

  for(i_sim in 1:settings$n_sim_bs)
  {
    w <- voipred:::bootstrap(n,settings$Bayesian_bootstrap)

    for(i in 1:length(zs))
    {
      bs_NBh_model1[i_sim,i] <- sum(w*(val_data$pi1>zs[i])*(val_data$Y - (1-val_data$Y)*zs[i]/(1-zs[i])))/n
      bs_NBh_model2[i_sim,i] <- sum(w*(val_data$pi2>zs[i])*(val_data$Y - (1-val_data$Y)*zs[i]/(1-zs[i])))/n
      bs_NBh_all[i_sim,i] <- sum(w*(val_data$Y - (1-val_data$Y)*zs[i]/(1-zs[i])))/n
      bs_max_NBh[i_sim,i] <- max(bs_NBh_model1[i_sim,i],bs_NBh_model2[i_sim,i],bs_NBh_all[i_sim,i],0)
    }
  }
  
  NBh_all <- colMeans(bs_NBh_all)
  NBh_model1 <- colMeans(bs_NBh_model1)
  NBh_model2 <- colMeans(bs_NBh_model2)
  max_NBh <- colMeans(bs_max_NBh)

  max_y <- max(0,NBh_all,NBh_model1,NBh_model2)
  plot(zs, NBh_all, col='black', type='l', ylim=c(0,max_y))
  lines(zs, NBh_model1, col='orange', type='l')
  lines(zs, NBh_model2, col='green', type='l')

  ci_model1 <- apply(bs_NBh_model1,MARGIN = 2,FUN = quantile, c(0.025,0.975))
  lines(zs,ci_model1[1,], type='l', col='gray')
  lines(zs,ci_model1[2,], type='l', col='gray')
  
  ci_model2 <- apply(bs_NBh_model2,MARGIN = 2,FUN = quantile, c(0.025,0.975))
  lines(zs,ci_model2[1,], type='l', col='gray')
  lines(zs,ci_model2[2,], type='l', col='gray')
  
  ENB_current <- pmax(NBh_all,NBh_model1,NBh_model2,0)
  ENB_perfect <- max_NBh
  
  lines(zs, ENB_perfect, col='red', type='l')
  lines(zs, ENB_current, col='black', type='l')
  #EVPI for validation:
  
  EVPIv_bs <- ENB_perfect-ENB_current
  plot(zs,EVPIv_bs,type='l', col='blue')
```







###  Reference modeling approach
```{R}
  bs_NB_model1 <- bs_NB_model2 <- bs_NB_all <- bs_max_NB <- bs_NB_max <- matrix(0, nrow=settings$n_sim_mb, ncol=length(zs))

  for(i_sim in 1:settings$n_sim_mb)
  {
    w_x <- voipred:::bootstrap(n,settings$Bayesian_bootstrap)
    val_data$w_y <- voipred:::bootstrap(n,settings$Bayesian_bootstrap)
    
    pop_model <- suppressWarnings(glm(formula = model2$call$formula, family=binomial(link="logit"), data=val_data, weights = w_y))
    
    p <- predict(pop_model, type="response", newdata = val_data)

    for(i in 1:length(zs))
    {
      bs_NB_model1[i_sim,i] <- sum(w_x*(val_data$pi1>zs[i])*(p - (1-p)*zs[i]/(1-zs[i])))/n
      bs_NB_model2[i_sim,i] <- sum(w_x*(val_data$pi2>zs[i])*(p - (1-p)*zs[i]/(1-zs[i])))/n
      bs_NB_all[i_sim,i] <- sum(w_x*(p - (1-p)*zs[i]/(1-zs[i])))/n
      bs_max_NB[i_sim,i] <- max(bs_NB_model1[i_sim,i],bs_NB_model2[i_sim,i],bs_NB_all[i_sim,i],0)
      bs_NB_max[i_sim,i] <- sum(w_x*((p>zs[i])*(p - (1-p)*zs[i]/(1-zs[i]))))/n
    }
  }

  ENB_current <- pmax(colMeans(bs_NB_all),colMeans(bs_NB_model1),colMeans(bs_NB_model2),0)
  ENBv_perfect <- colMeans(bs_max_NB)
  ENBd_perfect <- colMeans(bs_NB_max)
  EVPIv <- ENBv_perfect-ENB_current
  EVPId <- ENBd_perfect-ENB_current
  
  EINB_current <- (ENB_current-pmax(colMeans(bs_NB_all),0)) 
  EINBd_perfect <- (ENBd_perfect-pmax(colMeans(bs_NB_all),0))
  plot(zs,EINBd_perfect,col='red', type='l', main="EINBd")
  lines(zs,EINB_current)
  
  EINBv_perfect <- (ENBv_perfect-pmax(colMeans(bs_NB_all),0))
  plot(zs,EINBv_perfect,col='red', type='l', main="EINBv")
  lines(zs,EINB_current)
  
  EVPIdr <- EINBd_perfect/EINB_current
  plot(zs, EVPIdr, type='l', ylim=c(0,min(max(EVPIdr,na.rm=T),10)), main="EVPIdr")
  
  EVPIvr <- EINBv_perfect/EINB_current
  plot(zs, EVPIvr, type='l', ylim=c(0,min(max(EVPIvr,na.rm=T),10)), main="EVPIvr")

  plot(zs,EVPId,type='l', col='red', main = "EVPId")
  plot(zs,EVPIv,type='l', col='blue', main = "EVPIv")
  
  plot(zs,EVPId,type='l', col='red', main = "EVPId+EVPIv")
  lines(zs,EVPIv,type='l', col='blue')

  mean(EVPIv_bs)
  mean(EVPIv)
  mean(EVPId)
  
```


### At preferred threhsold

```{r}
EVPIv_bs[34]
EVPIv[34]
EVPId[34]
```



